<?php

// A list of github repos that are required by the Laravel framework.

$listOfRepositories = array(
    "briannesbitt/Carbon",
    "d11wtq/boris",
    "doctrine/common",
    "doctrine/dbal",
    "filp/whoops",
    "ircmaxell/password_compat",
    "jeremeamia/super_closure",
    "laravel/laravel",
    "laravel/framework",
    "mtdowling/ClassPreloader",
    "nikic/PHP-Parser",
    "nicolas-grekas/Patchwork-UTF8",
    "nrk/predis",
    "php-fig/log",
    "phpseclib/phpseclib",
    "sebastianbergmann/phpunit",
    "sebastianbergmann/php-code-coverage",
    "sebastianbergmann/php-file-iterator",
    "sebastianbergmann/php-text-template",
    "sebastianbergmann/php-timer",
    "sebastianbergmann/phpunit-mock-objects",
    "sebastianbergmann/php-code-coverage",
    "sebastianbergmann/php-token-stream",
    "Seldaek/monolog",
    "stackphp/builder",
    "swiftmailer/swiftmailer",
    "symfony/console",
    "symfony/CssSelector",
    "symfony/Debug",
    "symfony/EventDispatcher",
    "symfony/symfony",
    "symfony/BrowserKit",
    "symfony/DomCrawler",
    "symfony/Filesystem",
    "symfony/Finder",
    "symfony/HttpFoundation",
    "symfony/HttpKernel",
    "symfony/Process",
    "symfony/Routing",
    "symfony/Translation",  
);
